SUITS = ['spades', 'hearts', 'diamonds', 'clubs']
RANKS = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']

CARD_VALUES = {
    'A': 11,
    'J': 10, 'Q': 10, 'K': 10, '10': 10,
    '2': 2, '3': 3, '4': 4, '5': 5,
    '6': 6, '7': 7, '8': 8, '9': 9,
}

SUIT_SYMBOLS = {
    'spades':   '♠',
    'hearts':   '♥',
    'diamonds': '♦',
    'clubs':    '♣',
}

MIN_PLAYERS        = 2
MAX_PLAYERS        = 4
INITIAL_LIVES      = 3
FIRST_PLAYER_CARDS = 5
OTHER_PLAYER_CARDS = 4

ACTION_TAKE             = 'TAKE'
ACTION_DISCARD          = 'DISCARD'
ACTION_KNOCK            = 'KNOCK'
ACTION_INITIAL_DISCARD  = 'INITIAL_DISCARD'

SOURCE_DECK    = 'DECK'
SOURCE_DISCARD = 'DISCARD'

MSG_GAME_STATE      = 'GAME_STATE'
MSG_ACTION_REQ      = 'ACTION_REQ'
MSG_ACTION_RESP     = 'ACTION_RESP'
MSG_ROUND_END       = 'ROUND_END'
MSG_GAME_OVER       = 'GAME_OVER'
MSG_ERROR           = 'ERROR'
MSG_PLAYER_JOINED   = 'PLAYER_JOINED'
MSG_GAME_START      = 'GAME_START'

MSG_PING            = 'PING'
MSG_PONG            = 'PONG'

MSG_RECONNECT_REQ   = 'RECONNECT_REQ'
MSG_RECONNECT_OK    = 'RECONNECT_OK'
MSG_RECONNECT_FAIL  = 'RECONNECT_FAIL'

MSG_STATE_SYNC      = 'STATE_SYNC'
MSG_INVALID_PACKET  = 'INVALID_PACKET'

DEFAULT_HOST        = '0.0.0.0'
DEFAULT_PORT        = 5555
BUFFER_SIZE         = 4096
PING_INTERVAL_SEC   = 5
PING_TIMEOUT_SEC    = 15
RECONNECT_WINDOW_SEC = 60

LOG_FILE            = 'game_41.log'
LOG_LEVEL           = 'INFO'

LOG_EVENT_TAKE      = 'TAKE'
LOG_EVENT_DISCARD   = 'DISCARD'
LOG_EVENT_KNOCK     = 'KNOCK'
LOG_EVENT_ROUND_END = 'ROUND_END'
LOG_EVENT_GAME_OVER = 'GAME_OVER'
LOG_EVENT_CONNECT   = 'CONNECT'
LOG_EVENT_DISCONNECT= 'DISCONNECT'
LOG_EVENT_RECONNECT = 'RECONNECT'